import { v4 as uuid } from 'uuid';

import { TodoItem } from '@/types/todoItem';

// Generate date strings in YYYY-MM-DD format
const today = new Date().toISOString().split('T')[0];
const day1 = new Date(Date.now() + 24 * 60 * 60 * 1000)
  .toISOString()
  .split('T')[0];
const day2 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 2)
  .toISOString()
  .split('T')[0];
const day3 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 3)
  .toISOString()
  .split('T')[0];
const day4 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 4)
  .toISOString()
  .split('T')[0];
const day5 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 5)
  .toISOString()
  .split('T')[0];
const day6 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 6)
  .toISOString()
  .split('T')[0];
const day7 = new Date(Date.now() + 24 * 60 * 60 * 1000 * 7)
  .toISOString()
  .split('T')[0];

export const mockTodos: TodoItem[] = [
  {
    id: uuid(),
    title: 'Buy groceries',
    priority: 'MEDIUM',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Walk the dog',
    priority: 'LOW',
    completed: true,
    date: today,
  },
  {
    id: uuid(),
    title: 'Do laundry',
    priority: 'HIGH',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Finish homework',
    priority: 'HIGH',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Read a book',
    priority: 'LOW',
    completed: true,
    date: today,
  },
  {
    id: uuid(),
    title: 'Call mom',
    priority: 'HIGH',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Prepare dinner',
    priority: 'LOW',
    completed: true,
    date: today,
  },
  {
    id: uuid(),
    title: 'Clean the kitchen',
    priority: 'MEDIUM',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Pay bills',
    priority: 'HIGH',
    completed: false,
    date: today,
  },
  {
    id: uuid(),
    title: 'Exercise',
    priority: 'LOW',
    completed: true,
    date: today,
  },
  {
    id: uuid(),
    title: 'Water the plants',
    priority: 'MEDIUM',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Plan the weekend trip',
    priority: 'HIGH',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Update the resume',
    priority: 'LOW',
    completed: true,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Watch a tutorial',
    priority: 'MEDIUM',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Fix the leaking tap',
    priority: 'HIGH',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Meditate for 10 minutes',
    priority: 'LOW',
    completed: true,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Reply to emails',
    priority: 'HIGH',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Organize the closet',
    priority: 'MEDIUM',
    completed: false,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Schedule dentist appointment',
    priority: 'LOW',
    completed: true,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Take out the trash',
    priority: 'MEDIUM',
    completed: true,
    date: day1,
  },
  {
    id: uuid(),
    title: 'Make a to-do list for tomorrow',
    priority: 'HIGH',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Check the car tire pressure',
    priority: 'LOW',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Research on coding bootcamps',
    priority: 'MEDIUM',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Backup the laptop data',
    priority: 'HIGH',
    completed: true,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Organize photo albums',
    priority: 'LOW',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Go for a jog',
    priority: 'MEDIUM',
    completed: true,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Buy a birthday gift',
    priority: 'HIGH',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Cook lunch for the week',
    priority: 'LOW',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Take a coding test',
    priority: 'MEDIUM',
    completed: true,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Write a blog post',
    priority: 'HIGH',
    completed: false,
    date: day2,
  },
  {
    id: uuid(),
    title: 'Attend yoga class',
    priority: 'LOW',
    completed: true,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Shop for new shoes',
    priority: 'MEDIUM',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Send postcards',
    priority: 'HIGH',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Wash the car',
    priority: 'LOW',
    completed: true,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Install software updates',
    priority: 'MEDIUM',
    completed: true,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Buy dog food',
    priority: 'HIGH',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Plan a movie night',
    priority: 'LOW',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Research online courses',
    priority: 'MEDIUM',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Meet a friend for coffee',
    priority: 'HIGH',
    completed: true,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Tidy up the living room',
    priority: 'LOW',
    completed: false,
    date: day3,
  },
  {
    id: uuid(),
    title: 'Make a dentist follow-up',
    priority: 'MEDIUM',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Buy new notebooks',
    priority: 'HIGH',
    completed: true,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Design a mood board',
    priority: 'LOW',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Take medication',
    priority: 'MEDIUM',
    completed: true,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Order new supplies',
    priority: 'HIGH',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Set a budget plan',
    priority: 'LOW',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Repair the garden fence',
    priority: 'MEDIUM',
    completed: true,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Create a workout plan',
    priority: 'HIGH',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Write a thank-you letter',
    priority: 'LOW',
    completed: false,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Visit the library',
    priority: 'MEDIUM',
    completed: true,
    date: day4,
  },
  {
    id: uuid(),
    title: 'Organize a study session',
    priority: 'HIGH',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Send out invitations',
    priority: 'LOW',
    completed: true,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Get a haircut',
    priority: 'MEDIUM',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Refill prescriptions',
    priority: 'HIGH',
    completed: true,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Learn to cook a new recipe',
    priority: 'LOW',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Host a game night',
    priority: 'MEDIUM',
    completed: true,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Attend a webinar',
    priority: 'HIGH',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Organize kitchen cabinets',
    priority: 'LOW',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Create a meal plan',
    priority: 'MEDIUM',
    completed: true,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Take a photography walk',
    priority: 'HIGH',
    completed: false,
    date: day5,
  },
  {
    id: uuid(),
    title: 'Test a new app',
    priority: 'LOW',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Make a holiday shopping list',
    priority: 'MEDIUM',
    completed: true,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Donate old clothes',
    priority: 'HIGH',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Decorate for the holidays',
    priority: 'LOW',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Research pet insurance',
    priority: 'MEDIUM',
    completed: true,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Practice public speaking',
    priority: 'HIGH',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Start a new hobby',
    priority: 'LOW',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Organize email inbox',
    priority: 'MEDIUM',
    completed: true,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Send holiday cards',
    priority: 'HIGH',
    completed: false,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Book travel tickets',
    priority: 'LOW',
    completed: true,
    date: day6,
  },
  {
    id: uuid(),
    title: 'Create a vision board',
    priority: 'MEDIUM',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Make homemade gifts',
    priority: 'HIGH',
    completed: true,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Research stocks',
    priority: 'LOW',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Host a potluck dinner',
    priority: 'MEDIUM',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Practice coding challenges',
    priority: 'HIGH',
    completed: true,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Organize a volunteer event',
    priority: 'LOW',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Buy concert tickets',
    priority: 'MEDIUM',
    completed: true,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Try a new restaurant',
    priority: 'HIGH',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Organize work documents',
    priority: 'LOW',
    completed: false,
    date: day7,
  },
  {
    id: uuid(),
    title: 'Read financial news',
    priority: 'MEDIUM',
    completed: true,
    date: day7,
  },
];
